apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: vector
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    run: vector
status:
  loadBalancer: {}
